# theme
include dracula.conf

# fonts
font_family JetBrains Mono Regular Nerd Font
font_size 12
#disable_ligatures always
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# general
remember_window_size no
copy_on_select yes
map kitty_mod+period launch --type=overlay kitty +edit-config
enable_audio_bell no
update_check_interval 0

shell_integration disabled

# open_url
url_style single
mouse_map ctrl+left click grabbed,ungrabbed mouse_click_url

# carriage-return for zsh-autosuggestion \033 = ^[
map ctrl+enter send_text all \033[[CE

# key mappings fixes
map shift+enter send_text all \x0d
map shift+backspace send_text all \x7f
map shift+menu send_text all $
map ctrl+menu send_text all ^

# tab management
tab_bar_style powerline
map ctrl+shift+l new_tab_with_cwd
map ctrl+shift+k next_tab
map ctrl+shift+j previous_tab

# window management
enabled_layouts horizontal
map ctrl+alt+l launch --cwd=current
map ctrl+alt+k next_window
map ctrl+alt+j previous_window

# useful mappings for programming
map alt+è send_text all [
map alt+plus send_text all ]
map shift+alt+è send_text all {
map shift+alt+plus send_text all }
map alt+ì send_text all ~
map alt+ò send_text all @
map alt+à send_text all \u0023
map alt+' send_text all `
